export const WARDS = [
  'Ward 7D2',
  'Ward 9D',
  'Ward 6BIH-N1',
  'Ward 6BIH-N2',
  'Ward 6BIH-S1',
  'Ward 6BIH-S2',
  'Ward 6D1',
  'Ward 6D2',
  'Ward 6H',
  'Ward 6I',
  'Ward 6W',
  'Ward 7D1',
  'Ward 4W',
  'Ward 5BIH-N1',
  'Ward 5BIH-N2',
  'Ward 5BIH-S1',
  'Ward 5BIH-S2',
  'Ward 5H',
  'Ward 5I',
  'Ward 5W',
  'Ward 12D',
  'Ward 14D',
  'Ward 15D',
  'Ward 16D',
  'Ward 4BIH-N2',
  'Ward 4BIH-S1',
  'Ward 4BIH-S2',
  'ICU3',
  'ICU6',
  'ICU7',
  'ICU8',
  'Ward 10D',
  'Ward 11D',
  'CCU1-Sur',
  'CCU2-Med',
  'ICCU',
  'ICU1',
  'ICU2',
] as const

export type Ward = typeof WARDS[number]
